Treats/Models/Treat.cs
using System.Collections.Generic;

namespace Treats.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<TreatFlavor>();
    }

    public int TreatId {get; set;}
    public string TreatName {get; set;}
    public string Description {get; set;}

    public virtual ICollection<TreatFlavor> JoinEntities {get;}
  }
}

Treats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Treats.Models;
using System.Collections.Generic;
using System.Linq;

namespace Treats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly TreatsContext _db;

    public FlavorsController(TreatsContext db)
    {
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index() 
    { 
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = ("All Flavors's");
      List<Flavor> model = _db.Flavors.ToList();
      return View(model); 
    }
    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = ("Add New Flavor");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var model = _db.Flavors
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = (model.FlavorName);
      return View(model);
    }

    public ActionResult AddTreat(int id)
    {
      var model = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = ("Add A Treat!");
      return View(model);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if(TreatId != 0 && !_db.TreatFlavors.Any(model => model.FlavorId == flavor.FlavorId && model.TreatId == TreatId))
      {
        _db.TreatFlavors.Add(new TreatFlavor() {TreatId = TreatId, FlavorId = flavor.FlavorId});
        _db.SaveChanges();
      }
      return RedirectToAction("AddTreat");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId, int id) 
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View("Details", model);
    }

    public ActionResult Edit(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id );
      _db.Flavors.Remove(model);
      _db.SaveChanges();
      return RedirectToAction("Index");  
    }
  }
}

Treats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Treats.Models;
using System.Collections.Generic;
using System.Linq;

namespace Treats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly TreatsContext _db;

    public TreatsController(TreatsContext db)
    {
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index() 
    { 
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = ("All Treat's");
      List<Treat> model = _db.Treats.ToList();
      return View(model); 
    }

    public ActionResult Create()
    {
      ViewBag.PageTitle = ("Pierre's Treats");
      ViewBag.Header = ("Create a Treat!");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var model = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.PageTitle = ("Treat Details");
      ViewBag.Header = (@model.TreatName);
      return View(model);
    }

    public ActionResult AddFlavor(int id)
    {
      var model = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(model);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if(FlavorId != 0 && !_db.TreatFlavors.Any(model => model.TreatId == treat.TreatId && model.FlavorId == FlavorId))
      {
        _db.TreatFlavors.Add(new TreatFlavor() {FlavorId = FlavorId, TreatId = treat.TreatId});
        _db.SaveChanges();
      }
      return RedirectToAction("AddFlavor");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId, int id) 
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View("Details", model);
    }

    public ActionResult Edit(int id)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.PageTitle = ("Edit Treat");
      ViewBag.Header = ("Edit " + @model.TreatName);
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.PageTitle = ("Delete Treat");
      ViewBag.Header = ("Are you sure you want to delete " + @model.TreatName + "?");
      return View(model);
    }

    public ActionResult DeleteConfirmed(int id)
    {
      return DeleteConfirmed(id);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id, string v)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id );
      _db.Treats.Remove(model);
      _db.SaveChanges();
      return RedirectToAction("Index");  
    }
  }
}

Treats/Views/Treats/AddFlavor.cshtml
@{
  Layout="_Layout";
}

@model Treats.Models.Treat

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.Label("Add a Flavor")
  <br>
  @Html.DropDownList("FlavorId")
  <br>
  <br>
  <input type="submit" value="Add this Flavor" class="htmlButton"/>
}

@if(@Model.JoinEntities.Count == 0)
{
  <h3>No Flavors Are Assigned.</h3>
}
else
{

<br>
<h3>Current @Model.TreatName Flavor Profile:</h3>
  <table class="table table-bordered">
    @foreach(var join in Model.JoinEntities)
    {
      <tr>
        <td>
          @Html.ActionLink($"{join.Flavor.FlavorName}", "Details", "Flavors", new{id = join.Flavor.FlavorId})
        </td>
        <td style="width:10%">
          @using (Html.BeginForm("DeleteFlavor", "Treats"))
          {
            @Html.Hidden("joinId", @join.TreatFlavorId)
            @Html.Hidden("id", @Model.TreatId)
            <input type="submit" value="Remove Flavor"class="htmlButton"/>
          }
        </td>
      </tr>
    }
  </table>
}

<hr>
@Html.ActionLink("Return to Treat", "Details", "Treat", new{id = @Model.TreatId})

Treats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Treats.Models.Treat;

<h1>Add a Treat</h1>
@using(Html.BeginForm())
{
  @Html.TextBoxFor(model => model.TreatName, new{@class = "form-control", placeholder = "Enter the Treat name Here", required = "required"})
  <br>
  @Html.TextBoxFor(model => model.Description, new{@class = "form-control", placeholder = "Enter a Description Here", required = "required"})
  <br>
  <input type="submit" value="Add Treat" class="htmlButton"/>
}
<hr>
@Html.ActionLink("Return to Treats", "Index", "Treats", null, new { @class="htmlButton" })
@Html.ActionLink("Return Home", "Index", "Home", null, new { @class="htmlButton" })

Treats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Treats.Models.Treat;

<p>This Action is permanent</p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="htmlButton"/>
}
<hr>
@Html.ActionLink("Return to Treat List", "Index", "Treats", null, new { @class="htmlButton"})

Treats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model Treats.Models.Treat;

@if(@Model.JoinEntities.Count == 0)
{
  <p>No flavors associated with @Model.TreatName</p>
}
else 
{
  <h3>Flavor Profile:</h3>
  <table class="table table-bordered">
    @foreach(var join in Model.JoinEntities)
    {
      <tr>
        <td style="width:90%">
          @Html.ActionLink($"{join.Flavor.FlavorName}", "Details", "Flavors", new{id = join.Flavor.FlavorId})
        </td>
        <td style="width:10%">
          @using (Html.BeginForm("DeleteFlavor", "Treats"))
          {
            @Html.Hidden("joinId", @join.TreatFlavorId)
            @Html.Hidden("id", @Model.TreatId)
            <input type="submit" value="Remove from Treat" class="htmlButton"/>
          }
        </td>
      </tr>
    }
  </table>
}
<br>
<br>
@if(User.Identity.IsAuthenticated)
{
  @Html.ActionLink("Link a Flavor", "AddFlavor", "Treats", new { id = Model.TreatId }, new { @class="htmlButton" })
  @Html.ActionLink("Edit Treat", "Edit", "Treats", new { id = Model.TreatId }, new { @class="htmlButton" })
  @Html.ActionLink("Delete Treat", "Delete", "Treats",new { id = Model.TreatId }, new { @class="htmlButton" })
}

Treats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Treats.Models.Treat;

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Treat")
  <br>
  @Html.EditorFor(model => model.TreatName)
  <br><br>
  @Html.Label("Description")
  <br>
  @Html.EditorFor(model => model.Description)
  <br><br>
  <input type="submit" value="Save" class="htmlButton"/>
}
<hr>
@Html.ActionLink("Return to Treat List", "Index", "Treats", null, new { @class="htmlButton" })

Treats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Treats.Models;
@model List<Treats.Models.Treat>;

@if(@Model.Count == 0)
{
  <br>
  <p>No Treats Availible</p>
}
else
{
  <div class="row">
    <table class="table table-bordered table-hover">
      <thead>
        <th>Treat</th>
        <th>Description</th>
      </thead>
      <tbody>
        @foreach(var treat in Model)
        {
        <tr>
            <td>@Html.ActionLink($"{treat.TreatName}", "Details", "Treats", new{id = treat.TreatId})</td>
            <td>@treat.Description</td>
        </tr>
        }
      </tbody>
    </table>
  </div>
}
<br>
@if(User.Identity.IsAuthenticated)
{
  @Html.ActionLink("Add a Treat", "Create", "Treats", null, new { @class="htmlButton" })
  <br>
  <hr>
}
@Html.ActionLink("Return Home", "Index", "Home", null, new { @class="htmlButton" })